name: toyclient
description: "A simplified client to test WebSocket connections."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  web_socket_channel: ^2.4.5
  shared_preferences: ^2.2.3
  equatable: ^2.0.5 # Added for value equality

  # This is the key change. It tells Flutter to use the local 'shared' package.
  db_connection:
    path: ../db_connection
  shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
