name: carolina_card_club_server
description: A local RESTful server to manage the Carolina Card Club database.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  http: ^1.1.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
