name: carolina_card_club_server
description: The local server for the Carolina Card Club application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  # Web Server
  shelf: ^1.4.1
  shelf_router: ^1.1.4

  # WebSocket Handling
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3

  # Database
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0

  # Networking
  http: ^1.2.1

  # Local Shared Code
  shared:
    path: ../shared

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
